### ISSUE TITLE
Evaluate basecalling model

### ISSUE THREAD

**Issue by mbhall88** [mbhall88/head_to_head_pipeline#1]
(Proposed) Methods for evaluating the Mtb-specific guppy basecalling model.

## 1
Create a file mapping read IDs (for the evaluation reads) to the sample they come from.

## 2
Split the evaluation reads for each basecalling model into per-sample fastq files. This will result in two fastq files for each sample.

*Note: There is an inherit acceptance in this that the barcode assignment from the original guppy model is to be taken as "truth"*

## 3
Map each fastq to the reference assembly for that sample, using minimap2 (output PAF).  
Non-standard flags to use:
- `-c` generate CIGAR
- `-2` use two IO threads
- `--secondary=no` do not output secondary alignments

**Q**: Are we happy to ignore unmapped, secondary, and supplementary alignments? I think we should, but better to be explicit with this decision.

## 4
Calculate the ['BLAST identity'][blast] for each alignment. In PAF format, this is achieved by dividing column 10 (Number of matching bases in the mapping) by column 11 (Number bases, including gaps, in the mapping). BLAST identity is more suitable than [gap-compressed identity][gap-compression] for this assessment as we want the length of indels to affect the identity metric.

## 5
Generate assemblies with [Rebaler][rebaler]. Ryan specifically created Rebaler for assessing consensus accuracy when comparing basecalling models. It is effectively reference-guided assembly with some Racon polishing thrown in. i.e. uses the structure of the original assembly and replaces the bases with those from the reads.

## 6
Generate plots. The idea is to aggregate all data and plot for all samples together as we are assessing the model rather than the samples.
- [Violin plot of per-read BLAST identity.](https://github.com/rrwick/Basecalling-comparison/tree/95bf07476f61cda79e6971f20f48c6ac83e634b3#read-identity)
- BLAST identity vs read length. Density plots?
- [Relative read length as violin plot](https://github.com/rrwick/Basecalling-comparison/tree/95bf07476f61cda79e6971f20f48c6ac83e634b3#relative-read-length)
- Consensus accuracy. There are two ways I can conceive of visualising this. Either [as a violin plot, where each data point is a 10Kb chunk of the assembly](https://github.com/rrwick/Basecalling-comparison/tree/95bf07476f61cda79e6971f20f48c6ac83e634b3#assembly-identity) or as a single consensus value.
- Consensus sequence error types. [This plot][errors].

---

@iqbal-lab 
### Outstanding questions
- [ ] Should we also produce a plot of sequence errors at the read level? If so, would the best way to gather this be from CIGAR strings?
- [ ] Are we happy to ignore non-primary alignments for evaluation?
- [ ] How best to visualise BLAST identity vs read length?
- [ ] How best to visualise consensus accuracy?

As mentioned in the beginning, this is a proposal. Discuss anything else you think is missing or not needed.

[blast]: https://lh3.github.io/2018/11/25/on-the-definition-of-sequence-identity#blast-identity
[gap-compression]: https://lh3.github.io/2018/11/25/on-the-definition-of-sequence-identity#gap-compressed-identity
[rebaler]: https://github.com/rrwick/Rebaler
[errors]: https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1727-y#Fig3

**Comment by iqbal-lab** [comment]
1. i don't think we need a plot of seq errors at the read level
2. happy to ignore non-primary alignments
3. do we really need the consensus accuracy and assembly? i would be perfectly happy seeing a plot of BLAST identity, one histogram for the old basecalling and one for the new.

**Comment by mbhall88** [comment]
>     3. do we really need the consensus accuracy and assembly? i would be perfectly happy seeing a plot of BLAST identity, one histogram for the old basecalling and one for the new.

Yes. I think this info is very useful to know. And especially if we are going to make the model available to others. For instance, Chiron has lower read-level BLAST identity, but higher consensus-level BLAST identity than guppy.

**Comment by mbhall88** [comment]
Evaluation is done. See results [here](https://github.com/mbhall88/head_to_head_pipeline/tree/master/analysis/basecall_training#results)
