### ISSUE TITLE
Apply variants to H37Rv reference chunks

### ISSUE THREAD

**Issue by mbhall88** [mbhall88/head_to_head_pipeline#10]
For the dense and sparse H37Rv PRGs [#3] we need to add a certain amount of variants to our PRG. After we have ranked the variants with FORGe [#2] we can subset this ranking into dense and sparse.  
Then, for every variant in the ranking, we take the reference sequence for the "chunk" [#9] that position falls in and apply the variant to it. We then add the mutated sequence to a fasta file for that chunk.

**Comment by mbhall88** [comment]
I've found a corner case where some variants span two loci. It isn't immediately clear how I can handle this as indels cause problems (as always). For now, I am skipping any variant that starts/ends in two or more loci.
@iqbal-lab do you have another idea of how we can handle these?

**Comment by mbhall88** [comment]
Some summary information about the number of variants applied for the two different PRG types.

![image](https://user-images.githubusercontent.com/20403931/84856459-1adf6b80-b0aa-11ea-8382-67dfda25c830.png)

| prg_type   |   count |   mean |  std |   min |   25% |   50% |   75% |  max |
|:-----------|------------------------:|-----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|
| dense      |                    2582 |                62.0442 |               46.1961 |                     0 |                    34 |                    50 |                    76 |                   567 |
| sparse     |                    2582 |                21.4206 |               16.5244 |                     0 |                    11 |                    18 |                    27 |                   187 |

**Comment by iqbal-lab** [comment]
Nice plots. I have the following options for how to handle variants overlapping loci

1. Just lose them.
2. As 1, but choose your boundaries of loci to minimise the number of overlapping variants
3. Collect the list of variants that overlap the right hand end of a locus. Extend the locus to the right far enough to include them all (but do not add any other variants that fall into that region). When you genotype this locus you'll genotype these ones, which are strictly "to the left" of anything in the next locus on the right.

In this case, unusually for pandora, we have a strict ordering of loci - "normally" we would try to infer this from nanopore reads. 

I actually think 3 is error-prone in the general case with large indels overlapping edges. But if we restrict it to allowing small indels that overlap, it would prob work. 

I vote option 1 or 2

**Comment by mbhall88** [comment]
I have just come across an issue in #47 that originates from this step. **tl;dr: we need to restrict the length of insertions we add to the PRG**

In the process of trying to normalise the pandora VCF POS to H37Rv coordinates, I started seeing some strange behaviour. One of the checks I do is to confirm the H37Rv sequence that corresponds to the POS I am changing the variant to is the same as the REF column for that variant. However, in one example, `Rv3921c+Rv3922c+rnpA+rpmH` we had added an ALT variant from minos that was a 2956bp insertion. The eventual result of this is we lose the VCF reference for the loci in the PRG. And, indeed, if we look at the pandora log, we see

```
[2020-09-01 01:04:53.517456] [0x00002b570ba5c700] [warning] Input vcf_ref path did not start/end at the beginning/end of PRG Rv3921c+Rv3922c+rnpA+rpmH
[2020-09-01 01:04:53.517471] [0x00002b570ba5c700] [warning] Could not find reference sequence for Rv3921c+Rv3922c+rnpA+rpmH in the PRG so using the consensus path
```

**Comment by iqbal-lab** [comment]
What does it mean to lose the vcf ref?

**Comment by iqbal-lab** [comment]
Is this a fundamental pandora bug, or something to do with how you sliced the ref?

**Comment by mbhall88** [comment]
The VCF ref I am using for the pandora calls is the H37Rv sequence for the original loci chunk. Pandora requires that that sequence exists in the PRG. In this case, the sequence no longer exists in the PRG. Not sure if it is a bug or not though. The MSA can screw things up too I guess. As can make_prg. Regardless, we dont want to be adding 3kb indels...

**Comment by iqbal-lab** [comment]
So the start of this quote you say the vcf ref is H37Rv, and at the end you say it is not

"The VCF ref I am using for the pandora calls is the H37Rv sequence for the original loci chunk. Pandora requires that that sequence exists in the PRG. In this case, the sequence no longer exists in the PRG. The end result of this is that the REF for the variant in this loci is not consistent with H37Rv, as"

Sounds like we intend H37Rv to be the vcf ref but somehow cut it out at that variant when making the local prg?

**Comment by iqbal-lab** [comment]
Could this happen with a 1bp insertion?

**Comment by mbhall88** [comment]
> Sounds like we intend H37Rv to be the vcf ref but somehow cut it out at that variant when making the local prg?

Yes, it seems so.

> Could this happen with a 1bp insertion?

I don't think so? I am rerunning with max indel length of 20, so if I am still seeing this issue then we might have a bigger problem.
