### ISSUE TITLE
Multiple sequence alignment of "founder" variants

### ISSUE THREAD

**Issue by mbhall88** [mbhall88/head_to_head_pipeline#15]
After adding the founder variants to their respective H37Rv chunks[#10], run a MSA program (`clustalo`?) on each chunk.

**Comment by iqbal-lab** [comment]
fwiw, Brice is using mafft, but has not explored many tools. mafft generally considered fast afaik.
Aligning 2500 sequences of length 10kb takes an hour - should scale linearly with length and number of seq.

**Comment by mbhall88** [comment]
MAFFT is fast!
