### ISSUE TITLE
Run baseline variant calling for nanopore data

### ISSUE THREAD

**Issue by mbhall88** [mbhall88/head_to_head_pipeline#18]
The baseline variant calling for nanopore will be done with `bcftools` but using some filtering that will need experimenting.

**Comment by mbhall88** [comment]
After reading through [*Comparison of single-nucleotide variants identified by Illumina and Oxford Nanopore technologies in the context of a potential outbreak of Shiga toxin–producing Escherichia coli*][1] from David Greig and some reading elsewhere, I think we might want to use GATK to call variants for the nanopore data. This is open for discussion.

[1]: https://academic.oup.com/gigascience/article/8/8/giz104/5552683#140451498

**Comment by mbhall88** [comment]
In addition, Lachlan used nanopolish in [this][2] TB paper.

[2]: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6113869/

**Comment by mbhall88** [comment]
One nice thing about GATK is it's very customisable; so we can fine-tune the variant calls for this baseline analysis. David Greig did this to find the active profile score that best suited his data. I have combed through the GATK documentation, and I think the best program for us is `gatk HaplotypeCaller` (the replacement of `UnifiedGenotyper`). Parameters of interest are as follows

```
--assembly-region-padding:Integer
Number of additional bases of context to include around each assembly region  Default value: 100.

--base-quality-score-threshold:Byte
Base qualities below this threshold will be reduced to the minimum (6)  Default value: 18.

--exclude-intervals,-XL:String
One or more genomic intervals to exclude from processing  This argument may be specified 0 or more times. Default value: null.

--interval-exclusion-padding,-ixp:Integer
Amount of padding (in bp) to add to each interval you are excluding.  Default value: 0.

--max-assembly-region-size:Integer
Maximum size of an assembly region  Default value: 300.

--max-reads-per-alignment-start:Integer
Maximum number of reads to retain per alignment start position. Reads above this threshold will be downsampled. Set to 0 to disable.  Default value: 50.

--min-assembly-region-size:Integer
Minimum size of an assembly region  Default value: 50.

--min-base-quality-score,-mbq:Byte
Minimum base quality required to consider a base for calling  Default value: 10. Remove bases at each end of the read (hard-clipping) until there a base with a call quality equal or greater than minimum base quality score (customizable parameter -mbq, 10 by default).

--output-mode:OutputMode      
Specifies which type of calls we should output  Default value: EMIT_VARIANTS_ONLY. Possible values: {EMIT_VARIANTS_ONLY, EMIT_ALL_CONFIDENT_SITES, EMIT_ALL_ACTIVE_SITES}

--sample-ploidy,-ploidy:Integer
Ploidy (number of chromosomes) per sample. For pooled data, set to (Number of samples in each pool * Sample Ploidy).  Default value: 2.

--standard-min-confidence-threshold-for-calling,-stand-call-conf:Double
The minimum phred-scaled confidence threshold at which variants should be called  Default value: 30.0.

--active-probability-threshold:Double
Minimum probability for a locus to be considered active.  Default value: 0.002.

--adaptive-pruning:Boolean    
Use Mutect2's adaptive graph pruning algorithm  Default value: false. Possible values: {true, false} - DEFINITELY WANT TO SET THIS

--adaptive-pruning-initial-error-rate:Double
Initial base error rate estimate for adaptive pruning  Default value: 0.001.

--emit-ref-confidence,-ERC:ReferenceConfidenceMode
Mode for emitting reference confidence scores (For Mutect2, this is a BETA feature) Default value: NONE. Possible values: {NONE, BP_RESOLUTION, GVCF}

--kmer-size:Integer           
Kmer size to use in the read threading assembler  This argument may be specified 0 or more times. Default value: [10, 25].

--max-prob-propagation-distance:Integer
Upper limit on how many bases away probability mass can be moved around when calculating the boundaries between active and inactive assembly regions  Default value: 50.

--max-unpruned-variants:Integer
Maximum number of variants in graph the adaptive pruner will allow  Default value: 100.

--min-pruning:Integer         
Minimum support to not prune paths in the graph  Default value: 2.

--pcr-indel-model:PCRErrorModel
The PCR indel model to use  Default value: CONSERVATIVE. Possible values: {NONE, HOSTILE, AGGRESSIVE, CONSERVATIVE}

--phred-scaled-global-read-mismapping-rate:Integer
The global assumed mismapping rate for reads  Default value: 45.

```

Looking at their method, it seems quite similar (but obviously more fine-tuned) than the *de novo* process of pandora.

**Comment by iqbal-lab** [comment]
Fine with me. That's a lot of params to sweep though, but gatk usually have good docs. They got czi funding for bacterial variant calling so I hope they give best practice advice? Their human filtering used to rely on a machine learned black box. Mtbseq uses gatk.

**Comment by mbhall88** [comment]
I wasn't necessarily suggesting a parameter sweep. Just wanted to document params that could be useful to know about in case we want to tune anything.

I couldn't find any Bacterial best practises... I'll look a little harded.

**Comment by mbhall88** [comment]
Another interesting approach could be to take common SNPs found by running two variant callers (`bcftools` and `gatk`?). As an example, in [this 2013 paper from Comas](https://www.nature.com/articles/ng.2744) they took high-confidence calls from MAPQ and Samtools and considered common calls those where:
- they were common to both callers
- no more than two alleles at a position
- no het calls from either caller at position
- the position was not in a repetitive or mobile element

**Comment by mbhall88** [comment]
Should we also implement some kind of mapping quality threshold also? This does seem to be common in TB variant calling papers I have seen.
