### ISSUE TITLE
Excluding samples based on coverage

### ISSUE THREAD

**Issue by mbhall88** [mbhall88/head_to_head_pipeline#23]
Do we want to exclude samples based on coverage? If so, what threshold should we set?

The coverage for the nanopore data can be seen on a per-sample basis for the Malagasy and South African data in the below figures.

### TODO

- [x] add figures
- [x] get coverage information for Illumina data
- [x] provide stats on coverage at a project-wide level

**Comment by mbhall88** [comment]
### South Africa nanopore coverage data

![image](https://user-images.githubusercontent.com/20403931/86081927-f5a32200-bad9-11ea-89aa-ae0be79b54a8.png)

### Madagascar nanopore coverage data

![image](https://user-images.githubusercontent.com/20403931/86082289-b7f2c900-bada-11ea-89a8-465b4c13c489.png)

**Comment by mbhall88** [comment]
## Calculating coverage for Illumina data

Used [`fastq-scan`](https://github.com/rpetit3/fastq-scan) to do this.

From each site's data directory I ran

```sh
cd /hps/nobackup/research/zi/projects/tech_wars/data/madagascar
fd -d 1 -t d --threads 16 -x bash fastq-scan.sh '{}'/'{/.}'.R1.fastq.gz '{}'/'{/.}'.R2.fastq.gz '{}'/summary_stats.json \; '^mada_\d.*$' illumina/

cd /hps/nobackup/research/zi/projects/tech_wars/data/south_africa
fd -d 1 -t d --threads 16 -x bash fastq-scan.sh '{}'/'{/.}'.R1.fastq.gz '{}'/'{/.}'.R2.fastq.gz '{}'/summary_stats.json \; '^R\d+$' illumina/
```

The script being run is

```sh
#!/bin/bash

seqtk mergepe "$1" "$2" | fastq-scan -g 4411532 > "$3"
```

## Results
For all sites, broken down into technology

| | nanopore |  illumina |
|:------|--------------:|-----:|
| count | 187           | 200 |
| mean  | 119.859       | 129.836805 |
| std   | 104.261       | 53.315038 |
| min   |   0.000973358 | 42.839000 |
| 25%   |  39.1501      | 89.271100 |
| 50%   |  99.5842      |  119.049000 |
| 75%   | 166.389       | 163.402750 |
| max   | 483.593       | 291.338000 |


![image](https://user-images.githubusercontent.com/20403931/86087492-abc13880-bae7-11ea-8b4e-570d48d9cde1.png)

#### Nanopore
```
Coverage threshold 0x: 0 samples (0.0%) will be lost
Coverage threshold 10x: 15 samples (8.0%) will be lost
Coverage threshold 20x: 25 samples (13.4%) will be lost
Coverage threshold 30x: 38 samples (20.3%) will be lost
Coverage threshold 40x: 49 samples (26.2%) will be lost
Coverage threshold 50x: 57 samples (30.5%) will be lost
Coverage threshold 60x: 67 samples (35.8%) will be lost
Coverage threshold 70x: 74 samples (39.6%) will be lost
Coverage threshold 80x: 82 samples (43.9%) will be lost
Coverage threshold 90x: 86 samples (46.0%) will be lost
Coverage threshold 100x: 94 samples (50.3%) will be lost
```

#### Illumina

```
Coverage threshold 0x: 0 samples (0.0%) will be lost
Coverage threshold 10x: 0 samples (0.0%) will be lost
Coverage threshold 20x: 0 samples (0.0%) will be lost
Coverage threshold 30x: 0 samples (0.0%) will be lost
Coverage threshold 40x: 0 samples (0.0%) will be lost
Coverage threshold 50x: 5 samples (2.7%) will be lost
Coverage threshold 60x: 15 samples (8.0%) will be lost
Coverage threshold 70x: 22 samples (11.8%) will be lost
Coverage threshold 80x: 35 samples (18.7%) will be lost
Coverage threshold 90x: 53 samples (28.3%) will be lost
Coverage threshold 100x: 71 samples (38.0%) will be lost
```

**Comment by mbhall88** [comment]
Based on the above, I think all Illumina data has sufficient coverage, so it is just a matter of what minimum cutoff do we want for nanopore data....

**Comment by mbhall88** [comment]
We will reassess this at the end of the QC pipeline and look at coverage again. It is unlikely we will remove samples based on coverage (unless the coverage is something unworkable such as 1x).

**Comment by mbhall88** [comment]
Samples that failed their QC and the reasons can be found here: https://github.com/mbhall88/head_to_head_pipeline/blob/master/docs/failed_qc_reasons.md
45 samples failed QC, this is in addition to the 23 that were [excluded prior to QC](https://github.com/mbhall88/head_to_head_pipeline/blob/master/docs/failed_qc_reasons.md).

Bear in mind this is prior to addition of the MGIT Birmingham data

**Comment by mbhall88** [comment]
@iqbal-lab I am just assessing the Birmingham data after the QC pipeline and there are some Illumina samples with lower coverage than we had with Madagascar and SA. What would be your threshold for coverage for Illumina? We have 1 sample under 20x and 3 under 30x.

**Comment by iqbal-lab** [comment]
I think so long as you have >20x you are fine
