### ISSUE TITLE
Assign lineages for project samples

### ISSUE THREAD

**Issue by mbhall88** [mbhall88/head_to_head_pipeline#26]
This information will not doubt be useful at some point.

For now, probably easiest to use the lineage assignment script from the PRG building and the VCFs from COMPASS.

**Comment by mbhall88** [comment]
An overall view of the lineage assignments (individual assignments will be in the QC report).

## Major
```
     36 1
     61 2
     10 3
     62 4
      4 mixed
      5 unknown
```

## Full
```
     34 1.1.2
      2 1.2.2
     23 2.2
     26 2.2.1
      1 2.2.3
      3 2.2.6_RD150
      8 2.2.7
     10 3.1.1
      3 4
     17 4.10
     11 4.1.1.3
      3 4.1.2
     10 4.1.2.1
      3 4.1.3
      2 4.3.2.1
      1 4.3.3
      1 4.3.4.2.1
      6 4.4.1.1
      1 4.6.2.1
      4 4.6.2.2
      4 mixed
      5 unknown
```

cc @iqbal-lab

**Comment by mbhall88** [comment]
Individual assignment CSV files are located in `/hps/nobackup/research/zi/projects/tech_wars/data/QC/report/lineage_assignment`

**Comment by iqbal-lab** [comment]
Figure 1 here might be useful background in terms of what we expect
https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0200632
