### ISSUE TITLE
Concordance of baseline variant callers

### ISSUE THREAD

**Issue by mbhall88** [mbhall88/head_to_head_pipeline#38]
We will look at two different kinds of concordance:
1. Positions where COMPASS says ALT, how often does `bcftools` on nanopore agree?
2. At all positions where COMPASS "makes a statement", how often does `bcftools` on nanopore agree?

**Comment by mbhall88** [comment]
In the TAC2 report we said that the way we will represent concordance is 

> The results for this subsection will show concordance of the basic Nanopore variant calling with the Illumina truth set. We will discuss how the different filters trialled affected the results and plot recall against concordance.

@iqbal-lab  So, to clarify, recall will be Option 1 from above and concordance will be Option2?

**Comment by mbhall88** [comment]
Regarding recall, there is an outstanding question of *exactly* how to calculate this.

*a* = COMPASS  
*b* = `bcftools`  


Firstly, we need to calculate the denominator in recall. *T*. We take all positions where *a* **is not** masked or fail-filter and **is** ALT. **QUESTION**: do we **exclude** positions where *b* is NULL, FAIL-FILTER, HET, and MISSING?

After *T* has been determined. the numerator is easy enough to determine: number of positions in *T* where *b* agrees with *a*.

**Comment by mbhall88** [comment]
A similar question also remains for the calculation of concordance. i.e what sites do we **exclude** from contribution to concordance?

**Comment by iqbal-lab** [comment]
Answers

### So, to clarify, recall will be Option 1 from above and concordance will be Option2?
Yes

### For the recall denominator do we exclude positions where bcftools is NULL, FAIL-FILTER, HET, and MISSING?
yes to NULL, FAIL-FILTER, and MISSING
yes to HET, but good to notice if it is there but het.

### for concordance denominator
same

**Comment by mbhall88** [comment]
> yes to HET, but good to notice if it is there but het.

I slightly altered the output now so that I output the classification as before, but I also output the classification for each VCF at each position too. So we can shift our definitions of concordance/recall pretty easily now.

**Comment by mbhall88** [comment]
Here is an initial idea of concordance for different `bcftools` parameters and coverage (150x and 60x). **This is without any bcftools filtering**.

<table id="T_b37de6dc_cb1c_11ea_b8e7_9cb6d099c213" ><thead>    <tr>        <th class="blank level0" ></th>        <th class="col_heading level0 col0" >recall</th>        <th class="col_heading level0 col1" >concordance</th>    </tr></thead><tbody>                <tr>                        <th id="T_b37de6dc_cb1c_11ea_b8e7_9cb6d099c213level0_row0" class="row_heading level0 row0" >mada_112.60x.noindels.nobaq</th>                        <td id="T_b37de6dc_cb1c_11ea_b8e7_9cb6d099c213row0_col0" class="data row0 col0" >99.7230%</td>                        <td id="T_b37de6dc_cb1c_11ea_b8e7_9cb6d099c213row0_col1" class="data row0 col1" >99.9996%</td>            </tr>            <tr>                        <th id="T_b37de6dc_cb1c_11ea_b8e7_9cb6d099c213level0_row1" class="row_heading level0 row1" >mada_112.noindels.nobaq</th>                        <td id="T_b37de6dc_cb1c_11ea_b8e7_9cb6d099c213row1_col0" class="data row1 col0" >99.7230%</td>                        <td id="T_b37de6dc_cb1c_11ea_b8e7_9cb6d099c213row1_col1" class="data row1 col1" >99.9996%</td>            </tr>            <tr>                        <th id="T_b37de6dc_cb1c_11ea_b8e7_9cb6d099c213level0_row2" class="row_heading level0 row2" >mada_112.60x.noindels</th>                        <td id="T_b37de6dc_cb1c_11ea_b8e7_9cb6d099c213row2_col0" class="data row2 col0" >99.8615%</td>                        <td id="T_b37de6dc_cb1c_11ea_b8e7_9cb6d099c213row2_col1" class="data row2 col1" >99.9989%</td>            </tr>            <tr>                        <th id="T_b37de6dc_cb1c_11ea_b8e7_9cb6d099c213level0_row3" class="row_heading level0 row3" >mada_112.nobaq</th>                        <td id="T_b37de6dc_cb1c_11ea_b8e7_9cb6d099c213row3_col0" class="data row3 col0" >99.7230%</td>                        <td id="T_b37de6dc_cb1c_11ea_b8e7_9cb6d099c213row3_col1" class="data row3 col1" >99.9996%</td>            </tr>            <tr>                        <th id="T_b37de6dc_cb1c_11ea_b8e7_9cb6d099c213level0_row4" class="row_heading level0 row4" >mada_112.60x.nobaq</th>                        <td id="T_b37de6dc_cb1c_11ea_b8e7_9cb6d099c213row4_col0" class="data row4 col0" >99.7230%</td>                        <td id="T_b37de6dc_cb1c_11ea_b8e7_9cb6d099c213row4_col1" class="data row4 col1" >99.9996%</td>            </tr>            <tr>                        <th id="T_b37de6dc_cb1c_11ea_b8e7_9cb6d099c213level0_row5" class="row_heading level0 row5" >mada_112.60x</th>                        <td id="T_b37de6dc_cb1c_11ea_b8e7_9cb6d099c213row5_col0" class="data row5 col0" >99.8615%</td>                        <td id="T_b37de6dc_cb1c_11ea_b8e7_9cb6d099c213row5_col1" class="data row5 col1" >99.9989%</td>            </tr>            <tr>                        <th id="T_b37de6dc_cb1c_11ea_b8e7_9cb6d099c213level0_row6" class="row_heading level0 row6" >mada_112</th>                        <td id="T_b37de6dc_cb1c_11ea_b8e7_9cb6d099c213row6_col0" class="data row6 col0" >100.0000%</td>                        <td id="T_b37de6dc_cb1c_11ea_b8e7_9cb6d099c213row6_col1" class="data row6 col1" >99.9998%</td>            </tr>            <tr>                        <th id="T_b37de6dc_cb1c_11ea_b8e7_9cb6d099c213level0_row7" class="row_heading level0 row7" >mada_112.noindels</th>                        <td id="T_b37de6dc_cb1c_11ea_b8e7_9cb6d099c213row7_col0" class="data row7 col0" >100.0000%</td>                        <td id="T_b37de6dc_cb1c_11ea_b8e7_9cb6d099c213row7_col1" class="data row7 col1" >99.9998%</td>            </tr>    </tbody></table>

To be explicit, I link the lines of code that currently calculate [recall][recall] and [concordance][concor] and describe the exact way I have calculated them:

*a* = compass VCF
*b* = bcftools VCF
*F* = Dataframe containing 4 columns: position (F_p), a-classification (F_a), b-classification (F_b), overall-classification (F_o)

**Recall**: 

```
alt_calls = F where F_a is ALT
valid_alts = alt_calls where F_o is not in {Both Fail Filter, A Fails Filter, Masked}
called_alts = valid_alts where F_o is TrueAlt
recall = |called_alts| / |valid_alts|
```

**Concordance**:

```
total_calls = F where F_a is in {REF, ALT}
valid_calls = total_calls where F_o is not in {Both Fail Filter, A Fails Filter, Masked}
correct_calls = valid_calls where F_o is in {True Alt, True Ref}
concordance = |correct_calls| / |valid_calls|
```

A more thorough understanding can also be gained from looking through the [unit tests that test these two functions][tests].

---

@iqbal-lab these definitions do differ slightly to what you suggested above. In particular, I penalise bcftools in the following scenarios:
- compass makes a call; bcftools says NULL. If compass has made a call, then surely that suggests the data should be sufficient at this position to make a call?
- compass makes a call; bcftools fails FILTER. **This one I was a little unsure about**. In my mind, if we *exempt* positions where bcftools fails filtering, you could get perfect concordance by just filtering every position?
- compass makes a call; bcftools is missing the position. In the sample I've been working with, missing positions in bcftools are normally NULL in compass anyway
- compass makes a (non-het) call; bcftools makes a HET call. However, we use `--ploidy 1` so we won't actually get het calls from bcftools

[recall]: https://github.com/mbhall88/head_to_head_pipeline/blob/a9b9a65015df0bb7b10f84607221fac1341dcf6a/analysis/baseline_variants/nanopore/scripts/concordance.py#L217-L231
[tests]: https://github.com/mbhall88/head_to_head_pipeline/blob/a9b9a65015df0bb7b10f84607221fac1341dcf6a/analysis/baseline_variants/nanopore/scripts/test_concordance.py#L302-L556
[concor]: https://github.com/mbhall88/head_to_head_pipeline/blob/a9b9a65015df0bb7b10f84607221fac1341dcf6a/analysis/baseline_variants/nanopore/scripts/concordance.py#L233-L249

**Comment by iqbal-lab** [comment]
Those are pretty amazing results. I'll look more carefully over the day, but for now

#### compass makes a call; bcftools says NULL. If compass has made a call, then surely that suggests the data should be sufficient at this position to make a call?

No, compass is on illumina, bcftools is on nanopore


#### compass makes a call; bcftools fails FILTER. This one I was a little unsure about. In my mind, if we exempt positions where bcftools fails filtering, you could get perfect concordance by just filtering every position?

That's why you have two metrics
1. call rate - what % of the truth sites does bcftools say anything
2. concordance - how often is it right when it says something


#### compass makes a call; bcftools is missing the position. In the sample I've been working with, missing positions in bcftools are normally NULL in compass anyway

this will be seen in call rate/recall

#### compass makes a (non-het) call; bcftools makes a HET call. However, we use --ploidy 1 so we won't actually get het calls from bcftools

ok

**Comment by mbhall88** [comment]
> That's why you have two metrics

>    call rate - what % of the truth sites does bcftools say anything
>    concordance - how often is it right when it says something

Those definitions are quite different to https://github.com/mbhall88/head_to_head_pipeline/issues/38#issue-659929150 ...

**Comment by iqbal-lab** [comment]
Yes, you are right. I've just written and deleted a complicated comment comparing all these definitions. Let me suggest the following definitions which are an extension of what we have, and also have the benefit of being standard terms

#### Call rate (for true ALTs)
what % of true ALTs does bcftools make a REF/ALT call - anything except NULL and FILTER

#### Concordance (for true ALTs)
what % of true ALTs does bcftools  genotype agree with truth (excludes NULL, FILTER, *and* HET)

#### Genomewide Call rate
what % of true REF or ALT positions does bcftools make a REF/ALT call - anything except NULL and FILTER

#### Genomewide Concordance 
what % of true REF or ALT positions does bcftools  genotype agree with truth (excludes NULL, FILTER, *and* HET)

This includes the previous definitions, and (I think) clarifies and extends.
Concordance for true ALTs could be considered a "recall" of non-ref variants.

So, if bcftools is calling lots of NULLs we will see it in the call rate, and if it is getting genotypes wrong, we see it in concordance. The first concordance is about the 1000 or so non-ref positions; the second is dominated by loads of REF calls.

FYI - COMPASS aims to have a genomewide error rate of <1 per genome, and is willing to pay the price in call rate - they are happy to make calls in a small % of the genome at the price of ~all calls being right. So for bcftools, one would be aiming to have a super-high genome-wide concordance.

**Comment by mbhall88** [comment]
Great! Thanks, this makes a lot more sense now. I am assuming missing positions are classed the same as NULL/FILTER?

**Comment by iqbal-lab** [comment]
Yes, missing equals Null in my book. What else could it be? Oh...not in the vcf? Yrs, that too

**Comment by mbhall88** [comment]
> Yes, missing equals Null in my book. What else could it be? Oh...not in the vcf? Yrs, that too

Yeah, not in VCF. I.e. I guess minimap2 couldn't produce any primary alignments for that part of the genome.

**Comment by mbhall88** [comment]
Updated results with new definitions (no filtering):

<table id="T_84b40e1e_cbe2_11ea_ac7a_9cb6d099c213" ><thead>    <tr>        <th class="blank level0" ></th>        <th class="col_heading level0 col0" >call_rate</th>        <th class="col_heading level0 col1" >concordance</th>        <th class="col_heading level0 col2" >gw_call_rate</th>        <th class="col_heading level0 col3" >gw_concordance</th>    </tr></thead><tbody>                <tr>                        <th id="T_84b40e1e_cbe2_11ea_ac7a_9cb6d099c213level0_row0" class="row_heading level0 row0" >mada_112.60x.noindels.nobaq</th>                        <td id="T_84b40e1e_cbe2_11ea_ac7a_9cb6d099c213row0_col0" class="data row0 col0" >100.000000%</td>                        <td id="T_84b40e1e_cbe2_11ea_ac7a_9cb6d099c213row0_col1" class="data row0 col1" >99.722992%</td>                        <td id="T_84b40e1e_cbe2_11ea_ac7a_9cb6d099c213row0_col2" class="data row0 col2" >99.999975%</td>                        <td id="T_84b40e1e_cbe2_11ea_ac7a_9cb6d099c213row0_col3" class="data row0 col3" >99.999582%</td>            </tr>            <tr>                        <th id="T_84b40e1e_cbe2_11ea_ac7a_9cb6d099c213level0_row1" class="row_heading level0 row1" >mada_112.noindels.nobaq</th>                        <td id="T_84b40e1e_cbe2_11ea_ac7a_9cb6d099c213row1_col0" class="data row1 col0" >100.000000%</td>                        <td id="T_84b40e1e_cbe2_11ea_ac7a_9cb6d099c213row1_col1" class="data row1 col1" >99.722992%</td>                        <td id="T_84b40e1e_cbe2_11ea_ac7a_9cb6d099c213row1_col2" class="data row1 col2" >100.000000%</td>                        <td id="T_84b40e1e_cbe2_11ea_ac7a_9cb6d099c213row1_col3" class="data row1 col3" >99.999558%</td>            </tr>            <tr>                        <th id="T_84b40e1e_cbe2_11ea_ac7a_9cb6d099c213level0_row2" class="row_heading level0 row2" >mada_112.60x.noindels</th>                        <td id="T_84b40e1e_cbe2_11ea_ac7a_9cb6d099c213row2_col0" class="data row2 col0" >100.000000%</td>                        <td id="T_84b40e1e_cbe2_11ea_ac7a_9cb6d099c213row2_col1" class="data row2 col1" >99.861496%</td>                        <td id="T_84b40e1e_cbe2_11ea_ac7a_9cb6d099c213row2_col2" class="data row2 col2" >99.999189%</td>                        <td id="T_84b40e1e_cbe2_11ea_ac7a_9cb6d099c213row2_col3" class="data row2 col3" >99.999730%</td>            </tr>            <tr>                        <th id="T_84b40e1e_cbe2_11ea_ac7a_9cb6d099c213level0_row3" class="row_heading level0 row3" >mada_112.nobaq</th>                        <td id="T_84b40e1e_cbe2_11ea_ac7a_9cb6d099c213row3_col0" class="data row3 col0" >100.000000%</td>                        <td id="T_84b40e1e_cbe2_11ea_ac7a_9cb6d099c213row3_col1" class="data row3 col1" >99.722992%</td>                        <td id="T_84b40e1e_cbe2_11ea_ac7a_9cb6d099c213row3_col2" class="data row3 col2" >100.000000%</td>                        <td id="T_84b40e1e_cbe2_11ea_ac7a_9cb6d099c213row3_col3" class="data row3 col3" >99.999558%</td>            </tr>            <tr>                        <th id="T_84b40e1e_cbe2_11ea_ac7a_9cb6d099c213level0_row4" class="row_heading level0 row4" >mada_112.60x.nobaq</th>                        <td id="T_84b40e1e_cbe2_11ea_ac7a_9cb6d099c213row4_col0" class="data row4 col0" >100.000000%</td>                        <td id="T_84b40e1e_cbe2_11ea_ac7a_9cb6d099c213row4_col1" class="data row4 col1" >99.722992%</td>                        <td id="T_84b40e1e_cbe2_11ea_ac7a_9cb6d099c213row4_col2" class="data row4 col2" >99.999975%</td>                        <td id="T_84b40e1e_cbe2_11ea_ac7a_9cb6d099c213row4_col3" class="data row4 col3" >99.999582%</td>            </tr>            <tr>                        <th id="T_84b40e1e_cbe2_11ea_ac7a_9cb6d099c213level0_row5" class="row_heading level0 row5" >mada_112.60x</th>                        <td id="T_84b40e1e_cbe2_11ea_ac7a_9cb6d099c213row5_col0" class="data row5 col0" >100.000000%</td>                        <td id="T_84b40e1e_cbe2_11ea_ac7a_9cb6d099c213row5_col1" class="data row5 col1" >99.861496%</td>                        <td id="T_84b40e1e_cbe2_11ea_ac7a_9cb6d099c213row5_col2" class="data row5 col2" >99.999189%</td>                        <td id="T_84b40e1e_cbe2_11ea_ac7a_9cb6d099c213row5_col3" class="data row5 col3" >99.999730%</td>            </tr>            <tr>                        <th id="T_84b40e1e_cbe2_11ea_ac7a_9cb6d099c213level0_row6" class="row_heading level0 row6" >mada_112</th>                        <td id="T_84b40e1e_cbe2_11ea_ac7a_9cb6d099c213row6_col0" class="data row6 col0" >100.000000%</td>                        <td id="T_84b40e1e_cbe2_11ea_ac7a_9cb6d099c213row6_col1" class="data row6 col1" >100.000000%</td>                        <td id="T_84b40e1e_cbe2_11ea_ac7a_9cb6d099c213row6_col2" class="data row6 col2" >99.999975%</td>                        <td id="T_84b40e1e_cbe2_11ea_ac7a_9cb6d099c213row6_col3" class="data row6 col3" >99.999779%</td>            </tr>            <tr>                        <th id="T_84b40e1e_cbe2_11ea_ac7a_9cb6d099c213level0_row7" class="row_heading level0 row7" >mada_112.noindels</th>                        <td id="T_84b40e1e_cbe2_11ea_ac7a_9cb6d099c213row7_col0" class="data row7 col0" >100.000000%</td>                        <td id="T_84b40e1e_cbe2_11ea_ac7a_9cb6d099c213row7_col1" class="data row7 col1" >100.000000%</td>                        <td id="T_84b40e1e_cbe2_11ea_ac7a_9cb6d099c213row7_col2" class="data row7 col2" >99.999975%</td>                        <td id="T_84b40e1e_cbe2_11ea_ac7a_9cb6d099c213row7_col3" class="data row7 col3" >99.999779%</td>            </tr>    </tbody></table>

**Comment by mbhall88** [comment]
Current plots for concordance and call rate with depth are in this report: https://github.com/mbhall88/head_to_head_pipeline/blob/400a4c1ff81b06d22626f51224c6dd00df1b1a8a/analysis/baseline_variants/report.html

**Comment by mbhall88** [comment]
After filtering refinement using `varifier` (see https://github.com/mbhall88/head_to_head_pipeline/issues/39#issuecomment-673898811) we have a good checkpoint for the concordance at c645cd8. The report is uploaded to that commit along with all of the plots. A couple are pasted below.

# ALT concordance

![alt_concordance](https://user-images.githubusercontent.com/20403931/90218316-d02e6580-de46-11ea-907e-4e7fb0a019b1.png)

# Genome-wide concordance 

![gw_concordance](https://user-images.githubusercontent.com/20403931/90218399-0c61c600-de47-11ea-84aa-3257aff369b7.png)
