### ISSUE TITLE
Call per-sample variants with pandora

### ISSUE THREAD

**Issue by mbhall88** [mbhall88/head_to_head_pipeline#46]
Tasks that fall under this issue:

- [x] `pandora map` looking for *de novo* variants
- [x] update MSAs with discovered sequences
- [x] turn updated MSAs into PRGs (`make_prg`) 
- [x] index new PRG
- [x] `pandora map` **not** looking for *de novo* variants

**Comment by mbhall88** [comment]
An interesting analysis is to see whether *de novo* is "more active" when given a sparse PRG (as would be expected). That is, we would expected to see *de novo* finding *more* candidate regions in a sparse PRG compared to a dense one.  
To that end, I have taken the ratio of the number of candidate regions (that produce valid paths) for sparse vs. dense PRG (i.e. ratio is sparse/dense)

 0.9791_                                                                                                                                  
 0.9797_ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫
 0.9802_
 0.9807_
 0.9813_
 0.9818_
 0.9823_ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫
 0.9828_
 0.9834_
 0.9839_ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫
 0.9844_
 0.9850_
 0.9855_ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫
 0.9860_
 0.9865_ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫
 0.9871_ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫
 0.9876_ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫
 0.9881_ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫
 0.9887_ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫
 0.9892_ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫
 0.9897_ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫
 0.9903_ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫
 0.9908_ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫
 0.9913_ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫
 0.9918_ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫
 0.9924_ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫
 0.9929_ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫
 0.9934_ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫
 0.9940_ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫
 0.9945_ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫
 0.9950_ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫
 0.9955_ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫
 0.9961_ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫
 0.9966_ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫
 0.9971_ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫
 0.9977_ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫
 0.9982_ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫
 0.9987_ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫
 0.9992_ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫
 0.9998_ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫
 1.0003_ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫
 1.0008_
 1.0014_ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫
 1.0019_
 1.0024_ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫
 1.0029_
 1.0035_ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫
 1.0040_ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫
 1.0045_ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫
 1.0051_
 1.0056_ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫ ⃫
                                                                       ⃫
                                                                Tot:  1.50e+02
                                                                Avg:  9.93e-01
                                                                Std:  4.61e-03

So, we actually see *less* candidate regions in the sparse PRG...

**Comment by iqbal-lab** [comment]
What was the trigger for detecting a candidate region again? More than N bases with depth==0? No, you switched to something looking at the ratio of coverages of adjacent bases?

**Comment by mbhall88** [comment]
> What was the trigger for detecting a candidate region again? More than N bases with depth==0? No, you switched to something looking at the ratio of coverages of adjacent bases?

https://github.com/rmcolq/pandora/pull/141

**Comment by mbhall88** [comment]
Update MSAs rule ran 300 jobs in 40 minutes. Max. memory job was 1.5Gb. Longest running job was 33 minutes.

**Comment by mbhall88** [comment]
Run `make_prg` on all updated MSAs and combine all local PRGs into a single PRG took 20 minutes to run 600 jobs. Max memory was ~1.5Gb.

**Comment by iqbal-lab** [comment]
On one or many cores?

**Comment by mbhall88** [comment]
> On one or many cores?

Each job had 16 cores. So for each sample, 16 `make_prg`s running concurrently
