### ISSUE TITLE
Add minimum FRS filter

### ISSUE THREAD

**Issue by mbhall88** [mbhall88/head_to_head_pipeline#62]
Off the back of the analysis in #61 we need to add a filter for both pandora and bcftools to filter based on the minimum fraction of support on the called allele. This is because, at least for pandora (see #61), a large number of our FP calls are due to positions where Illumina/compass filters due to HET calls or low support for the called base.

**Comment by mbhall88** [comment]
I have run the FRS filter with and without a bunch of other filters and here are the results on the 7 validation samples

**X-axis label key**

- `none`: no filters
- `0ea6325`: the commit of pandora where I implemented the cluster size expectation fix (https://github.com/rmcolq/pandora/issues/262). The filters for this label are min covg 3, min gt conf 15, strand bias 0.01
- `K<float>`: Minimum FRS threshold of `<float>` and the same filters as `0ea6325` (i.e the same filters we were using before the FRS filter was added)
- `K<float>-only`: Minimum FRS threshold of `<float>` and no other filters
- `K<float>s1`: Min. FRS `<float>` and strand bias 0.01 (i.e 1%)
- `K<float>s1d3`: As above with min covg 3
- `K<float>s1d3g5`: As above with min. GT_CONF of 5
- `nodenovo`: Pandora with no de novo variant calling (note: this is prior to the cluster size fix, but with the same filters as `0ea6325`)

## SNP recall

![image](https://user-images.githubusercontent.com/20403931/108618200-c6299700-7467-11eb-96fa-2f2b040f2b63.png)

## SNP precision

![image](https://user-images.githubusercontent.com/20403931/108618348-0a696700-7469-11eb-9fe4-d72d4e578720.png)

## Indel recall

![image](https://user-images.githubusercontent.com/20403931/108618356-16edbf80-7469-11eb-8ada-da9ca89256d8.png)

## Indel precision

![image](https://user-images.githubusercontent.com/20403931/108618357-20772780-7469-11eb-81dd-13063e25502b.png)

## All variants recall

*Note: compass and bcftools only call SNPs*

![image](https://user-images.githubusercontent.com/20403931/108618364-2ec54380-7469-11eb-9902-7c9d50e913ef.png)

## All variants precision

![image](https://user-images.githubusercontent.com/20403931/108618370-4c92a880-7469-11eb-9507-309ca52ec46e.png)

---

I am in the process of rerunning bcftools with the min. FRS filter also.

**Comment by mbhall88** [comment]
Filters:
- Min. FRS 0.85
- Strand bias 1%
- Min. coverage 3
- Min. GT conf 5

## Close dotplot

![close_dotplot_K0 85s1d3g5](https://user-images.githubusercontent.com/20403931/108641459-14cc4500-74eb-11eb-8a45-abe7ba329ec8.png)

## Full dotplot


![dotplot_K0 85s1d3g5](https://user-images.githubusercontent.com/20403931/108641682-442f8180-74ec-11eb-8679-d6920784fa9e.png)

**Comment by iqbal-lab** [comment]
Looks great. V glad to see tight distribution of orange near zero. Hope this results on pretty congruent clusters

**Comment by mbhall88** [comment]
I was actually thinking it might make sense to use different filters for compare? The current ones could be a little harsh?

**Comment by iqbal-lab** [comment]
No harm in looking (what actually are prexision and recall for Pandora compare?), but being a bit brutal, all we need is for, in the range "compass distance <=10", we need Pandora distance to be < some small X, and in the range "Pandora distance <=X" ideally no extra dots. Ie we just need to deliver the same or v similar clusters

**Comment by mbhall88** [comment]
Pandora Filters:
- Min. FRS 0.85
- Strand bias 1%
- Min. coverage 3
- Min. GT conf 5

## Close dotplot

![close_dotplot_K0 9s1d3g5](https://user-images.githubusercontent.com/20403931/108670563-cb9be580-752a-11eb-93aa-4585c35dd59c.png)

## Full dotplot

![dotplot_K0 9s1d3g5](https://user-images.githubusercontent.com/20403931/108670582-d35b8a00-752a-11eb-9db5-802eb3e8dca8.png)

**Comment by mbhall88** [comment]
Keeping the current bcftools filters and addinf a minimum FRS of 0.9 leads to the following improvements (note: the recall has slightly increased compared to the previous filters - I think this is because that was an older version of varifier)

## Precision

![image](https://user-images.githubusercontent.com/20403931/108801134-9f42a080-75e0-11eb-8a56-072d4234efe4.png)

## Recall

![image](https://user-images.githubusercontent.com/20403931/108801141-a5d11800-75e0-11eb-9863-d31d587263c9.png)

**Comment by mbhall88** [comment]
After re-running bcftools with the new FRS filters we get the following results. *Note: I realised halfway through that I had since changed the varifier version too, so I included the intermediate results to see the effect of the new varifier version*

## Recall

![image](https://user-images.githubusercontent.com/20403931/108802986-40cbf100-75e5-11eb-9c52-9e387728485e.png)

## Precision

![image](https://user-images.githubusercontent.com/20403931/108802993-445f7800-75e5-11eb-9ae3-a21ccfef4b82.png)

**Comment by mbhall88** [comment]
The (close) dotplot before and after FRS for bcftools (this is FRS 0.85)

## Before FRS - bcftools

![bcftools_dotplot_old](https://user-images.githubusercontent.com/20403931/108805293-7ffd4080-75eb-11eb-9995-ac7087b81a32.png)

## With FRS 0.85 - bcftools

![bcftools_dotplot_frs0 85](https://user-images.githubusercontent.com/20403931/108805483-b2a73900-75eb-11eb-875b-a86d99d1cc60.png)


## All callers with FRS

![close_dotplot_frs0 85](https://user-images.githubusercontent.com/20403931/108805720-c2268200-75eb-11eb-9503-29917cf6d42a.png)

**Comment by iqbal-lab** [comment]
Something weird with your x axis tickmarks on latest recall and precision. Second tickmark along has no label. Means second box plot has no label?

**Comment by mbhall88** [comment]
No, they're correct. The labels are on a 45-degree angle. So you kind of go up from the middle of the label text.
