### ISSUE TITLE
Reproducing "truth" Illumina clusters using genome graphs and nanopore

### ISSUE THREAD

**Issue by mbhall88** [mbhall88/head_to_head_pipeline#7]
In this section, we will calculate the pairwise SNP distance between all pairs of samples, using the truth set from the baseline variant calling [#4]. We will then do the same using the `pandora` variant calls [#6] from whichever PRG we decide provides the best results.  
The main figure for this subsection will be a dot plot where each dot is a pair and the X- and Y-axes are the pairwise distance for that pair according to the truth set and `pandora`, respectively. In a perfect world, we would expect to see a dead-straight diagonal line from the bottom-left to top-right. In reality, we hope to see a general linear trend. A linear trend would allow us to state that although specific SNP distance thresholds used to define clusters differ between technologies, they are relative and therefore one can use Nanopore data with `pandora` to generate epidemiological clusters for Mtb.

**Comment by mbhall88** [comment]
Page 199 of [this](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/821334/Tuberculosis_in_England-annual_report_2019.pdf) PHE TB report states that PHE use a SNP threshold of 12 to identify clusters.

**Comment by mbhall88** [comment]
Some useful resources when thinking about comparing clusters (these resources actually compare distance matrices)
- https://www.datanovia.com/en/lessons/comparing-cluster-dendrograms-in-r/
- https://en.wikipedia.org/wiki/Mantel_test
- https://en.wikipedia.org/wiki/Distance_correlation

**Comment by mbhall88** [comment]
The dotplots with bcftools, pandora-single (i.e. per-sample), and pandora-multi (i.e. pandora compare)

## Full

![full_dotplot](https://user-images.githubusercontent.com/20403931/106538559-2653aa00-6548-11eb-884e-c40cfd509fd5.png)

## Close (within 100bp)

![close_dotplot](https://user-images.githubusercontent.com/20403931/106538626-42574b80-6548-11eb-82c2-83e67d74e45d.png)

### Conclusion

The current distances from `pandora compare` are not good, and especially for close (as judged by compass) samples.

**Comment by iqbal-lab** [comment]
If you pick a few pairs of  samples where compass says they are very close, but pandora compare says they are far (200 snps apart or whatever) what are the 200 SNPs? Are they in one gene or across the genome? Do they have low gt conf? Are they in low coverage samples? If so this might be improved by gcp. Are they SNPs ? If yes, what happens when you restrict to SNPs? 

By the way, in terms of the value of pandora compare,  the intention is that pandora chooses its reference so that the maximum number of variants appear as snps. So restricting to SNPs and comparing with compass is like measuring the value if what pandora has done. Compass restricts to snps with respect to h37rv. We would be restricting to snps with respect to our reference.  

The fact that pandora compare adds effectively a fixed distance to all (best fit does not go through origin) is interesting.  But we need some concrete info on the close pairs to be able to interpret

**Comment by mbhall88** [comment]
See https://nbviewer.jupyter.org/github/mbhall88/head_to_head_pipeline/blob/master/analysis/transmission_clustering/eda/multisample_distance_debugging.ipynb for answers to (I think) most of those questions.

In summary, I will restrict to SNPs first and see how that changes things.

Would be happy to hear your input from the plots in that notebook though. I hope it is clear enough what is happening in each section?

**Comment by iqbal-lab** [comment]
Well done doing that so fast! V interesting.  V relieved the results good for SNPs. More questions 

1.For the non SNPs,  are the results equally bad for "real' indels and for things where both ref and alt alleles are long? 

2. Any chance of plotting counts of FPs along the genome (in case we/kerri can spot enrichment in bad regions)


3. Could you also show FPs compared with the mask?


4. If there are lots of errors where both alleles are long (pandora might call them phased snps), are they loci where there are just two alleles (one ref and one alt), or ones where there are many? If the latter, this is sort of good news. One major reason for developing brices nested genotyping algorithm was to improve genotyping when you have lots of long alleles.  Pandora just uses mean coverage across the whole allele, so many alleles differing by SNPs are hard to distinguish. 

Overall I'm v relieved this looks like we can probably get snp distances that correlate with compass.  The fact using pandora compare introduces a minimum distance implies to me one of two things 

1. Either some subtle issue with the dynamic programming for the vcf ref, introducing a systematic error. I don't quite see what error would do this though.  If it chose a reference that was actually a bit further from all samples at one locus,  not sure how it'd introduce a snp difference there.

2. Or, we genotype badly at sites with many long alleles (eg 14 alleles differing by 6 snps) which I've expected but not seen before.  Brice's algorithm would fix that, but beyond scope of your paper. If so, probably you are ok for dst indels

If neither of those....not sure,need to think.

**Comment by mbhall88** [comment]
I have added a section at the bottom of the above notebook in response to your questions.

> Well done doing that so fast! V interesting. V relieved the results good for SNPs. More questions
> 
> 1.For the non SNPs, are the results equally bad for "real' indels and for things where both ref and alt alleles are long?

In the VCFs I am working with, there aren't many "long" alleles in the VCFs where the calls are different for the two samples when they should have been the same. However, I have left-aligned and normalised these VCFs so that may not reflect their original lengths.

However, if we look at the same positions in the original VCF, there still doesn't seem to be a striking enrichment for "long" alleles for alternate or reference alleles. If anything, the ones where we get it wrong have shorter alleles

> 
>     2. Any chance of plotting counts of FPs along the genome (in case we/kerri can spot enrichment in bad regions)
> 
>     3. Could you also show FPs compared with the mask?

To both points above: it seems like there is no real enrichment in bad regions (also remember we masked the genome in PRG construction so a lot of those mask positions aren't even in the picture for us)

> 
>     4. If there are lots of errors where both alleles are long (pandora might call them phased snps), are they loci where there are just two alleles (one ref and one alt), or ones where there are many? If the latter, this is sort of good news. One major reason for developing brices nested genotyping algorithm was to improve genotyping when you have lots of long alleles.  Pandora just uses mean coverage across the whole allele, so many alleles differing by SNPs are hard to distinguish.

In addition to my answer to question 1, there does not seem to be an increase in the number of alternate alleles at sites where we get the pairwise distance wrong.

> 
> 
> Overall I'm v relieved this looks like we can probably get snp distances that correlate with compass. The fact using pandora compare introduces a minimum distance implies to me one of two things
> 
>     1. Either some subtle issue with the dynamic programming for the vcf ref, introducing a systematic error. I don't quite see what error would do this though.  If it chose a reference that was actually a bit further from all samples at one locus,  not sure how it'd introduce a snp difference there.
> 
>     2. Or, we genotype badly at sites with many long alleles (eg 14 alleles differing by 6 snps) which I've expected but not seen before.  Brice's algorithm would fix that, but beyond scope of your paper. If so, probably you are ok for dst indels
> 
> 
> If neither of those....not sure,need to think.

**Comment by mbhall88** [comment]
**Commit d5828c32392b34e254040d7d45d047c2b659c176**

In this dotplot, the `pandora compare` VCF has had all uncalled ALTs removed, normalised (with [`bcftools norm`](https://samtools.github.io/bcftools/bcftools.html#norm)) and then removed any record that was not a SNP. By "not a SNP" we remove a record if *any* of REF/ALT is more than 1 base.

## Close (within 100bp)

![multisample_snps_dotplot](https://user-images.githubusercontent.com/20403931/107340721-cf327400-6b09-11eb-8684-abfb26618956.png)

### Conclusion

This looks dramatically better than in [the previous plot](https://github.com/mbhall88/head_to_head_pipeline/issues/7#issuecomment-771276593). However, there are still plenty of concerning outliers, which are easily visible on both the plot and in the correlation coefficient.

### Next step

Look at some of the outlier pairs to see what could be causing the discrepancy.

**Comment by iqbal-lab** [comment]
Are outlier pairs for pandora the same as the outlier pairs for bcftools? i notice both tools have the same number of outliers, could be a shared cause

**Comment by mbhall88** [comment]
The big, obvious outliers (in the top-left) are the same between the two. The middle-top ones are also the same, but I'd hesitate to call them outliers in the bcftools data. However, there are a lot of under-called outliers that don't seem to have corresponding bcftools outliers.

**Comment by iqbal-lab** [comment]
Great. I wonder if the big obvious top left outliers in both bcftools and Pandora are driven by the same snps/ reasons for both. Eg low coverage, or systematic nanopore issues

**Comment by mbhall88** [comment]
They definitely aren't coverage-related as all of those samples have high coverage (unless that is an issue). I am going to dig into them today :+1:

**Comment by mbhall88** [comment]
See https://github.com/rmcolq/pandora/issues/262 for the work up until now on this issue

**Comment by mbhall88** [comment]
The 6 outliers in the top-left of the dotplots all have a single sample in common: `mada_1-11`. I ran mykrobe on the Illumina and Nanopore data for this sample to see if there is lineage/dst discrepancies that could explain the massive difference between the two distances.

### DST

The nanopore data shows as susceptible for all drugs. However, the Illumina data has resistance for Ethambutol - but I think it's a HET call potentially?

```json
             "Ethambutol": {
                 "predict": "r",
                 "called_by": {
                     "embB_M306L-ATG4247429CTG": {
                         "variant": null,
                         "genotype": [
                             0,
                             1
                         ],
                         "genotype_likelihoods": [
                             -410.17929609333845,
                             -40.82331566903429,
                             -872.7181935569092
                         ],
                         "info": {
                             "coverage": {
                                 "reference": {
                                     "percent_coverage": 100.0,
                                     "median_depth": 13,
                                     "min_non_zero_depth": 12,
                                     "kmer_count": 266,
                                     "klen": 21
                                 },
                                 "alternate": {
                                     "percent_coverage": 100.0,
                                     "median_depth": 8,
                                     "min_non_zero_depth": 6,
                                     "kmer_count": 153,
                                     "klen": 21
                                 }
                             },
                             "expected_depths": [
                                 26
                             ],
                             "contamination_depths": [],
                             "filter": [],
                             "conf": 369
                         },
                         "_cls": "Call.VariantCall"
                     }
                 }
             },
```

This position is a HET call in the compass VCF, so we ignore it for distance calculations. In the bcftools VCF it is a ref call but we filter it as it is low quality. In the pandora single sample VCF, the variant is in the list of ALTs and has more coverage than the other ALTs but is lower than coverage of the REF. It's the same story in the compare VCF.

### Lineage

The Illumina data is called as lineages 2.26 and 2.2.7, whereas the nanopore data is called as 2.2.6.

**Comment by mbhall88** [comment]
The DST information for `mada_1-11` is as follows

### Culture

Resistant: Isoniazid, Rifampin, Thioacetazone

### Hain

Resistant: Rifampin

### WGS

This is a little interesting. When I use *all* the Illumina data (i.e. not just the decontaminated QC data) I get a het call for Ethambutol as above, but also a het call for Rifampicin

```json
            "Ethambutol": {
                "predict": "r",
                "called_by": {
                    "embB_M306L-ATG4247429CTG": {
                        "variant": null,
                        "genotype": [
                            0,
                            1
                        ],
                        "genotype_likelihoods": [
                            -683.8516125986662,
                            -228.19742333566705,
                            -3615.1477306295255
                        ],
                        "info": {
                            "coverage": {
                                "reference": {
                                    "percent_coverage": 100.0,
                                    "median_depth": 53,
                                    "min_non_zero_depth": 50,
                                    "kmer_count": 1055,
                                    "klen": 21
                                },
                                "alternate": {
                                    "percent_coverage": 100.0,
                                    "median_depth": 17,
                                    "min_non_zero_depth": 15,
                                    "kmer_count": 339,
                                    "klen": 21
                                }
                            },
                            "expected_depths": [
                                79.0
                            ],
                            "contamination_depths": [],
                            "filter": [],
                            "conf": 456
                        },
                        "_cls": "Call.VariantCall"
                    }
                }
            },
            "Rifampicin": {
                "predict": "r",
                "called_by": {
                    "rpoB_H445R-CAC761139CGC": {
                        "variant": null,
                        "genotype": [
                            0,
                            1
                        ],
                        "genotype_likelihoods": [
                            -667.5341891498271,
                            -219.2720528376126,
                            -3277.7416963796964
                        ],
                        "info": {
                            "coverage": {
                                "reference": {
                                    "percent_coverage": 100.0,
                                    "median_depth": 46,
                                    "min_non_zero_depth": 44,
                                    "kmer_count": 931,
                                    "klen": 21
                                },
                                "alternate": {
                                    "percent_coverage": 100.0,
                                    "median_depth": 16,
                                    "min_non_zero_depth": 15,
                                    "kmer_count": 301,
                                    "klen": 20
                                }
                            },
                            "expected_depths": [
                                79.0
                            ],
                            "contamination_depths": [],
                            "filter": [],
                            "conf": 448
                        },
                        "_cls": "Call.VariantCall"
                    }
                }
            },
```

**Comment by mbhall88** [comment]
**Commit https://github.com/mbhall88/pandora/commit/0ea6325d21b7d311ee3834bd10469565995e2903**

I have run the cluster size estimation fix (https://github.com/rmcolq/pandora/issues/262) on all single-sample cases. The results on the dotplot are quite striking.

*Remember the pandora_single is using `map` instead of `compare` to call variants*

# Close dotplot

## Before

![before](https://user-images.githubusercontent.com/20403931/107915696-b36b1a00-6fb0-11eb-958d-0f3a116df664.png)

## After

![after](https://user-images.githubusercontent.com/20403931/107915746-ca117100-6fb0-11eb-852e-db91ec01d8f7.png)

Note the difference on the y-axis!

# Full dotplot

## Before

![full_before](https://user-images.githubusercontent.com/20403931/107915938-24123680-6fb1-11eb-8926-24f7f221ef16.png)

## After

![full_after](https://user-images.githubusercontent.com/20403931/107915959-2d030800-6fb1-11eb-9714-d47d329a7004.png)
