### ISSUE TITLE
Concordance of resistance predictions with phenotype

### ISSUE THREAD

**Issue by mbhall88** [mbhall88/head_to_head_pipeline#76]
We do not have phenotype data for every sample/drug, so just for those we do have.  
Similar to #75, we will have a table showing Very Major Error (missed resistance), Major Error (missed susceptible), PPV (what % of R calls are R) and NPV (what % of S calls are S) for each tool.

**Comment by mbhall88** [comment]
First draft of the figure for this analysis

---

## Figure 2
Number of resistant (left) and susceptible (right) phenotypes correctly identified by mykrobe from Illumina (blue) and Nanopore (purple) data from the same samples. The red bars indicate missed (FN) or incorrect (FP) predictions. The x-axis shows the drugs with available phenotype data that mykrobe also makes predictions for. E - ethambutol; H - isoniazid; Z - pyrazinamide; R - rifampicin; S - streptomycin; Km - kanamycin; Am - amikacin; Ofx - ofloxacin; Cm - capreomycin; Mfx - moxifloxacin.

![image](https://user-images.githubusercontent.com/20403931/124700035-51935880-df2f-11eb-9040-7060a9040d3c.png)

**Comment by mbhall88** [comment]
We could conceivable also use a table (or replace the figure with a table if more informative)

|    | drug         | technology   |        NPV |        PPV |   sensitivity |   specificity |   ME/FP |   VME/FN |   TP |   TN |
|---:|:-------------|:-------------|-----------:|-----------:|--------------:|--------------:|--------:|---------:|-----:|-----:|
|  0 | Amikacin     | Illumina     |   0.974026 |   0.818182 |      0.818182 |      0.974026 |       2 |        2 |    9 |   75 |
|  1 | Amikacin     | Nanopore     |   1        |   0.846154 |      1        |      0.974026 |       2 |        0 |   11 |   75 |
|  2 | Capreomycin  | Illumina     |   1        |   0        |    nan        |      0.980392 |       1 |        0 |    0 |   50 |
|  3 | Capreomycin  | Nanopore     |   1        |   0        |    nan        |      0.980392 |       1 |        0 |    0 |   50 |
|  4 | Ethambutol   | Illumina     |   0.9375   |   0.384615 |      0.714286 |      0.789474 |      16 |        4 |   10 |   60 |
|  5 | Ethambutol   | Nanopore     |   0.939394 |   0.416667 |      0.714286 |      0.815789 |      14 |        4 |   10 |   62 |
|  6 | Isoniazid    | Illumina     |   0.849057 |   0.933333 |      0.84     |      0.9375   |       3 |        8 |   42 |   45 |
|  7 | Isoniazid    | Nanopore     |   0.854167 |   0.86     |      0.86     |      0.854167 |       7 |        7 |   43 |   41 |
|  8 | Kanamycin    | Illumina     |   1        |   0        |    nan        |      0.980392 |       1 |        0 |    0 |   50 |
|  9 | Kanamycin    | Nanopore     |   1        |   0        |    nan        |      0.980392 |       1 |        0 |    0 |   50 |
| 10 | Moxifloxacin | Illumina     | nan        |   0        |    nan        |      0        |       1 |        0 |    0 |    0 |
| 11 | Moxifloxacin | Nanopore     | nan        |   0        |    nan        |      0        |       1 |        0 |    0 |    0 |
| 12 | Ofloxacin    | Illumina     |   1        |   0.714286 |      1        |      0.947368 |       4 |        0 |   10 |   72 |
| 13 | Ofloxacin    | Nanopore     |   1        |   0.714286 |      1        |      0.947368 |       4 |        0 |   10 |   72 |
| 14 | Pyrazinamide | Illumina     |   1        | nan        |    nan        |      1        |       0 |        0 |    0 |    1 |
| 15 | Pyrazinamide | Nanopore     |   1        | nan        |    nan        |      1        |       0 |        0 |    0 |    1 |
| 16 | Rifampicin   | Illumina     |   0.877551 |   0.97619  |      0.87234  |      0.977273 |       1 |        6 |   41 |   43 |
| 17 | Rifampicin   | Nanopore     |   0.877551 |   0.97619  |      0.87234  |      0.977273 |       1 |        6 |   41 |   43 |
| 18 | Streptomycin | Illumina     |   0.935065 |   0.230769 |      0.375    |      0.878049 |      10 |        5 |    3 |   72 |
| 19 | Streptomycin | Nanopore     |   0.960526 |   0.357143 |      0.625    |      0.890244 |       9 |        3 |    5 |   73 |

**Comment by iqbal-lab** [comment]
Cool! So essentially identical results except slightly better VME for animating, and slightly worse for isoniazid  . I call that a win

**Comment by iqbal-lab** [comment]
Wait a minute,  how come pyrazinamide is in the table, I thought we didn't have any phenotypes for that? Did I forget/get that wrong???

**Comment by mbhall88** [comment]
> Wait a minute, how come pyrazinamide is in the table, I thought we didn't have any phenotypes for that? Did I forget/get that wrong???

We have 1 sample with PZA DST haha. Maybe I just leave it out then?

**Comment by mbhall88** [comment]
Here is another plot that is very insightful

Effect of Nanopore read depth on mykrobe phenotype prediction. Each point indicates the proportion (y-axis) of classifications of that type at the read depth (x-axis). Read depth is "binned". That is, read depth 40 is all samples with a read depth greater than 40 and less than or equal to 50.

![image](https://user-images.githubusercontent.com/20403931/124712667-f66b6100-df42-11eb-9c53-7450ed95b17e.png)

**Comment by iqbal-lab** [comment]
For this table https://github.com/mbhall88/head_to_head_pipeline/issues/76#issuecomment-875270092
we will need to have confidence intervals, eg see https://www.nature.com/articles/ncomms10063/tables/1

**Comment by mbhall88** [comment]
I don't really understand where the confidence intervals come from? The values aren't the result of any kind of aggregation/averaging...

**Comment by iqbal-lab** [comment]
The confidence intervals inform you how much you can trust the rate (FPR, VME, whatever) based on the number of samples.
A TPR of 90% is more confident if you find 9900 out of 10000 resistant samples than if you find 9 out of 10.
This stuff (confidence intervals) always does my head in a bit though, so don't worry when you look up the definitions and they confuse the hell out of you.

**Comment by mbhall88** [comment]
I see. Ok, I've added that in using the [Wilson score interval](https://en.wikipedia.org/wiki/Binomial_proportion_confidence_interval#Wilson_score_interval) - which is the same as was used in the recent mykrobe paper. However, I notice the Nature Comms paper used [Clopper–Pearson confidence interval](https://en.wikipedia.org/wiki/Binomial_proportion_confidence_interval#Clopper%E2%80%93Pearson_interval). Although I don't think the two are that different.

**Comment by mbhall88** [comment]
## Table 2 Comparison of Nanopore drug resistance predictions with Illumina predictions

For this comparison, we assume the mykrobe resistance prediction from Illumina data is correct and evaluate the Nanopore prediction accordingly.

FN=false negative; R=number of resistant samples; FP=false positive; S=number of susceptible samples; FNR=false negative rate; FPR=false positive rate; PPV=positive predictive value; NPV=negative predictive value; CI=Wilson score confidence interval

| Drug          | FN(R)   | FP(S)   | FNR(95% CI)      | FPR(95% CI)       | PPV(95% CI)          | NPV(95% CI)          |
|:--------------|:--------|:--------|:-----------------|:------------------|:---------------------|:---------------------|
| Amikacin      | 0(12)   | 2(138)  | 0.0% (0.0-24.2%) | 1.4% (0.4-5.1%)   | 85.7% (60.1-96.0%)   | 100.0% (97.3-100.0%) |
| Capreomycin   | 0(12)   | 2(138)  | 0.0% (0.0-24.2%) | 1.4% (0.4-5.1%)   | 85.7% (60.1-96.0%)   | 100.0% (97.3-100.0%) |
| Ciprofloxacin | 1(17)   | 0(133)  | 5.9% (1.0-27.0%) | 0.0% (0.0-2.8%)   | 100.0% (80.6-100.0%) | 99.3% (95.9-99.9%)   |
| Ethambutol    | 2(56)   | 0(94)   | 3.6% (1.0-12.1%) | 0.0% (0.0-3.9%)   | 100.0% (93.4-100.0%) | 97.9% (92.7-99.4%)   |
| Isoniazid     | 0(80)   | 7(70)   | 0.0% (0.0-4.6%)  | 10.0% (4.9-19.2%) | 92.0% (84.3-96.0%)   | 100.0% (94.3-100.0%) |
| Kanamycin     | 0(13)   | 2(137)  | 0.0% (0.0-22.8%) | 1.5% (0.4-5.2%)   | 86.7% (62.1-96.3%)   | 100.0% (97.2-100.0%) |
| Moxifloxacin  | 1(17)   | 0(133)  | 5.9% (1.0-27.0%) | 0.0% (0.0-2.8%)   | 100.0% (80.6-100.0%) | 99.3% (95.9-99.9%)   |
| Ofloxacin     | 0(17)   | 0(133)  | 0.0% (0.0-18.4%) | 0.0% (0.0-2.8%)   | 100.0% (81.6-100.0%) | 100.0% (97.2-100.0%) |
| Pyrazinamide  | 1(31)   | 0(119)  | 3.2% (0.6-16.2%) | 0.0% (0.0-3.1%)   | 100.0% (88.6-100.0%) | 99.2% (95.4-99.9%)   |
| Rifampicin    | 0(78)   | 0(72)   | 0.0% (0.0-4.7%)  | 0.0% (0.0-5.1%)   | 100.0% (95.3-100.0%) | 100.0% (94.9-100.0%) |
| Streptomycin  | 2(46)   | 2(104)  | 4.3% (1.2-14.5%) | 1.9% (0.5-6.7%)   | 95.7% (85.5-98.8%)   | 98.1% (93.3-99.5%)   |

---

One thing I have changed from the mykrobe papers is the use of FNR/FPR instead of VME/ME. I find VME and ME confusing. Happy to change it back though if this is an issue

**Comment by mbhall88** [comment]
I've also overlayed sample size for the coverage plot

![image](https://user-images.githubusercontent.com/20403931/125156362-6595bf00-e1a8-11eb-9f8a-33880232439b.png)

**Comment by iqbal-lab** [comment]
Channeling my inner Michael patrolling appropriate slack channels...
This issue is about concordance with phenotype,  and this comment

https://github.com/mbhall88/head_to_head_pipeline/issues/76#issuecomment-877591309

Is about concordance with illumina, which is a different issue.

**Comment by mbhall88** [comment]
Ah, right you are. Thank you!

**Comment by mbhall88** [comment]
Something interesting to know about mykrobe - when using a diploid model for ONT it goes crazy and calls **everything** resistant to Isoniazid. Looking at a few samples, it looks like it calls a whole bunch of indels as HET

![image](https://user-images.githubusercontent.com/20403931/125180483-071b2000-e23e-11eb-86d2-9970bb0113fa.png)

**Comment by mbhall88** [comment]
I am going to start writing the results section with the following final (pending major issues) plot and table

![image](https://user-images.githubusercontent.com/20403931/125232338-bed42e80-e31f-11eb-9b9b-26a0df2091fc.png)

| Drug         | Technology   | FN(R)   | FP(S)   | FNR(95% CI)        | FPR(95% CI)        | PPV(95% CI)        | NPV(95% CI)          |
|:-------------|:-------------|:--------|:--------|:-------------------|:-------------------|:-------------------|:---------------------|
| Amikacin     | Illumina     | 2(11)   | 2(77)   | 18.2% (5.1-47.7%)  | 2.6% (0.7-9.0%)    | 81.8% (52.3-94.9%) | 97.4% (91.0-99.3%)   |
| Amikacin     | Nanopore     | 0(11)   | 2(77)   | 0.0% (0.0-25.9%)   | 2.6% (0.7-9.0%)    | 84.6% (57.8-95.7%) | 100.0% (95.1-100.0%) |
| Capreomycin  | Illumina     | 0(0)    | 1(51)   | -                  | 2.0% (0.3-10.3%)   | 0.0% (0.0-79.3%)   | 100.0% (92.9-100.0%) |
| Capreomycin  | Nanopore     | 0(0)    | 1(51)   | -                  | 2.0% (0.3-10.3%)   | 0.0% (0.0-79.3%)   | 100.0% (92.9-100.0%) |
| Ethambutol   | Illumina     | 3(14)   | 16(76)  | 21.4% (7.6-47.6%)  | 21.1% (13.4-31.5%) | 40.7% (24.5-59.3%) | 95.2% (86.9-98.4%)   |
| Ethambutol   | Nanopore     | 4(14)   | 14(76)  | 28.6% (11.7-54.6%) | 18.4% (11.3-28.6%) | 41.7% (24.5-61.2%) | 93.9% (85.4-97.6%)   |
| Isoniazid    | Illumina     | 8(50)   | 3(48)   | 16.0% (8.3-28.5%)  | 6.2% (2.1-16.8%)   | 93.3% (82.1-97.7%) | 84.9% (72.9-92.1%)   |
| Isoniazid    | Nanopore     | 7(50)   | 7(48)   | 14.0% (7.0-26.2%)  | 14.6% (7.2-27.2%)  | 86.0% (73.8-93.0%) | 85.4% (72.8-92.8%)   |
| Kanamycin    | Illumina     | 0(0)    | 1(51)   | -                  | 2.0% (0.3-10.3%)   | 0.0% (0.0-79.3%)   | 100.0% (92.9-100.0%) |
| Kanamycin    | Nanopore     | 0(0)    | 1(51)   | -                  | 2.0% (0.3-10.3%)   | 0.0% (0.0-79.3%)   | 100.0% (92.9-100.0%) |
| Ofloxacin    | Illumina     | 0(10)   | 4(76)   | 0.0% (-0.0-27.8%)  | 5.3% (2.1-12.8%)   | 71.4% (45.4-88.3%) | 100.0% (94.9-100.0%) |
| Ofloxacin    | Nanopore     | 0(10)   | 4(76)   | 0.0% (-0.0-27.8%)  | 5.3% (2.1-12.8%)   | 71.4% (45.4-88.3%) | 100.0% (94.9-100.0%) |
| Rifampicin   | Illumina     | 5(47)   | 1(44)   | 10.6% (4.6-22.6%)  | 2.3% (0.4-11.8%)   | 97.7% (87.9-99.6%) | 89.6% (77.8-95.5%)   |
| Rifampicin   | Nanopore     | 6(47)   | 1(44)   | 12.8% (6.0-25.2%)  | 2.3% (0.4-11.8%)   | 97.6% (87.7-99.6%) | 87.8% (75.8-94.3%)   |
| Streptomycin | Illumina     | 5(8)    | 10(82)  | 62.5% (30.6-86.3%) | 12.2% (6.8-21.0%)  | 23.1% (8.2-50.3%)  | 93.5% (85.7-97.2%)   |
| Streptomycin | Nanopore     | 3(8)    | 9(82)   | 37.5% (13.7-69.4%) | 11.0% (5.9-19.6%)  | 35.7% (16.3-61.2%) | 96.1% (89.0-98.6%)   |

**Comment by iqbal-lab** [comment]
The results in the latest plot
https://github.com/mbhall88/head_to_head_pipeline/issues/76#issuecomment-877966555

are noticeably worse than the previous plot
https://github.com/mbhall88/head_to_head_pipeline/issues/76#issuecomment-875266622

We used to do better for isoniazid VME (FNs) and now not @mbhall88 ?
