### ISSUE TITLE
Submit data to the ENA

### ISSUE THREAD

**Issue by mbhall88** [mbhall88/head_to_head_pipeline#83]

**Comment by mbhall88** [comment]
Study is registered with accession PRJEB49093

**Comment by mbhall88** [comment]
@iqbal-lab I am working on registering the samples for the study and the only piece of [mandatory metadata](https://www.ebi.ac.uk/ena/browser/view/ERC000028) I can't infer for the Birmingham data is collection date. Are you able to get this?

**Comment by mbhall88** [comment]
Another question regarding the metadata. "Strain" is not mandatory, but recommened, would this be the best place to put lineage information?

**Comment by iqbal-lab** [comment]
Apologies, I can ask Tim peto about collection date. I am belatedly worrying if the Birmingham data has been independently submitted. 

Re strain, will ask. Have never seen lineage in there

**Comment by mbhall88** [comment]
> Apologies, I can ask Tim peto about collection date. I am belatedly worrying if the Birmingham data has been independently submitted.
> 
> Re strain, will ask. Have never seen lineage in there

Yeah, if they have been uploaded already (I assume only the Illumina will have been) I will need study and/or sample accessions. I am assuming the Nanopore data won't have been uploaded so I will still need the collection date for those - although I can steal that info from the Illumina ENA entries if they have already been uploaded.
