### ISSUE TITLE
RIF and INH off-catalogue mutations

### ISSUE THREAD

**Issue by mbhall88** [mbhall88/head_to_head_pipeline#85]
In the interest of documenting this - as it will be useful for reviews potentially, and especially for the `drprg` paper - here is more tantalising information about the phenotype concordance FNs for INH and RIF.

There are 9 INH FNs. I have [previously pointed out that 6 of these have a mutation R463L (g1388t, NC_000962.3:c2154724a)](https://github.com/mbhall88/head_to_head_pipeline/issues/80#issuecomment-955637418), which is not in the catalogue. We see this mutation in 4/6 RIF FNs.
In addition, 4/6 (3 the same as above and one different) RIF FNs have an rpoB mutation A1075A (t3225c, NC_000962.3:t763031c) (`mada_1-17, mada_1-18, mada_1-11, mada_1-33`). This is very interesting. This mutation is considered a Beijing lineage marker and is a synonymous mutation. So most people have just said it isn’t associated with resistance. BUT a recent paper ([1]) highlighted that this mutation is more prevalent in RR isolates. It has also been mentioned in other papers ([2], [3], [4]).
One sample (`mada_1-17`), in addition to R463L in katG and A1075A in rpoB also has a 6bp deletion in rpoB. This one is tricky as the deletion spans multiple codons and as such, mykrobe didn’t pick it up because it only encodes 1-2bp indels (@iqbal-lab might find this interesting).

The 6 samples with RIF FNs: `mada_1-11, mada_1-12, mada_1-17, mada_1-18, mada_1-33, mada_1-50`
The 9 INH FNs include the 6 RR samples above, plus: `mada_1-2, mada_1-21, mada_1-6`

[1]: https://www.frontiersin.org/articles/10.3389/fmicb.2020.01444/full?report=reader
[2]: https://www.sciencedirect.com/science/article/pii/S1876034118300418
[3]: https://www.researchgate.net/profile/Nguyen-Bach/publication/281265005_Characteristics_of_IS6110_sequence_and_association_between_gene_mutation_and_multidrug_resistant_M_tuberculosis_strain_isolated_in_Central_Vietnam/links/55dd667008ae591b309ad280/Characteristics-of-IS6110-sequence-and-association-between-gene-mutation-and-multidrug-resistant-M-tuberculosis-strain-isolated-in-Central-Vietnam.pdf
[4]: https://academic.oup.com/jac/article/66/4/730/723098?login=true

**Comment by mbhall88** [comment]
Another comment, I noticed that katG R463L was used as a phylogenetic marker in the NEJM paper (considered susceptible). See the NEJM appendix https://www.nejm.org/doi/suppl/10.1056/NEJMoa1800474/suppl_file/nejmoa1800474_appendix.pdf

**Comment by mbhall88** [comment]
It would be very interesting to go through the NEJM data and see how prevalent these two mutations are in R vs S isolates

**Comment by mbhall88** [comment]
Further interesting informaion about the *rpoB A1075A* mutation. As I said, it is treated as a Beijing lineage marker (Lineage 2). However, the four samples with this mutation have varying lineages

| sample | lineage |
| --- | --- |
| mada_1-33 | 1.1.2
|mada_1-18 | 1.1.2
mada_1-11 | 2.2 |
|mada_1-17 | 3.1.1 |

**Comment by iqbal-lab** [comment]
What's the prevalence of this snp in the full cryptic 12k?

**Comment by mbhall88** [comment]
For `rpoB_A1075A` it's present in 56.4% (8580/15211) samples.  
For `katG_R463L` it's present in 56.3% (8565/15211) samples.  
These two variants co-occur in 8557 samples - so effectively they always co-occur.

**Comment by mbhall88** [comment]
When I go through the samples that have phenotypes I get the following contingency tables

| | `katG_R463L` present |  `katG_R463L` absent |
| --- | --- | ---|
| **INH R** | 2999 | 2093 |
| **INH S** | 2540 | 3306 |

| | `rpoB_A1075` present |  `rpoB_A1075` absent |
| --- | --- | ---|
| **RIF R** | 2763 | 2021 |
| **RIF S** | 3023 | 3567 |

My statistics knowledge is not brilliant and I am struggling to find a test that will tell us if these mutations are more prevalent in resistant samples. Any ideas @iqbal-lab ?
